INSERT INTO status VALUES (NULL,"NEW"),(NULL,"ACCEPTED"),(NULL,"PROCESSING"),(NULL,"COMPLETE"),(NULL,"AVAILABLE"),(NULL,"UNAVAILABLE");
INSERT INTO major VALUES (NULL,"Both"),(NULL,"Software"),(NULL,"Hardware")
