INSERT INTO status VALUES (NULL,"NEW"),(NULL,"ACCEPTED"),(NULL,"PROCESSING"),(NULL,"COMPLETE"),(NULL,"CANCEL"),(NULL,"TMPCANCEL"),(NULL,"TMPCOMPLETE"),(NULL,"DEACTIVE");
INSERT INTO major VALUES (NULL,"Software"),(NULL,"Hardware")
